### PR TITLE
[bio] add support for django 1.9.6

### PR DESCRIPTION
**Pull request by akoshochrein**
Had some time to do this yesterday evening. Let's bump!

@prezi/bio @pierrei @szaboat @ghoranyi

### CODE REVIEW

**Comment by balazs-tothfalussy** [comment]
seems fine, +1

**Comment by szaboat** [comment]
Where do we use 1.9.x?

**Comment by akoshochrein** [comment]
Nowhere yet, this PR allows the bump

**Comment by pierrei** [comment]
Cool! If it works, it all looks good to me :) 👍

**Pull request closed without merging**
